apiVersion: apps/v1
kind: Deployment
metadata:
  name: approbation-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approbation-frontend
  template:
    metadata:
      labels:
        app: approbation-frontend
    spec:
      containers:
      - name: frontend
        image: seifeddineabidi/approbation-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://approbation-backend:8080"
        - name: RECAPTCHA_SITE_KEY
          value: "6LdDuhcrAAAAAHrytAMLMiwP_PGlS7y_cAKQMqHn"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5