apiVersion: apps/v1
kind: Deployment
metadata:
  name: approbation-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approbation-frontend
  template:
    metadata:
      labels:
        app: approbation-frontend
    spec:
      containers:
      - name: frontend
        image: seifeddineabidi/approbation-frontend:latest
        ports:
        - containerPort: 80