apiVersion: apps/v1
kind: Deployment
metadata:
  name: approbation-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approbation-frontend
  template:
    metadata:
      labels:
        app: approbation-frontend
    spec:
      containers:
      - name: frontend
        image: seifeddineabidi/approbation-frontend:c1dca03cc9a60a928751572a6f969fe86d365291
        ports:
        - containerPort: 80