apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: approbation-frontend-ingress
  namespace: default  # Should match your application namespace
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Specify the ingress class
    nginx.ingress.kubernetes.io/rewrite-target: /  # Rewrite the URL path as needed
spec:
  rules:
  - host: approbation.example.com  # Replace with your actual domain or use wildcard
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: approbation-frontend-service  # The name of your frontend service
            port:
              number: 80  # Port the service is exposed on
