   apiVersion: v1
   kind: Service
   metadata:
     name: approbation-frontend
     namespace: default
   spec:
     selector:
       app: approbation-frontend
     ports:
     - port: 80
       targetPort: 80
       nodePort: 30080
     type: NodePort