# k8s-manifests/frontend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: approbation-frontend
spec:
  selector:
    app: approbation-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP 
