apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: default
type: Opaque
data:
  username: cm9vdA==  # base64 encoded "root"
  password: cm9vdA==  # base64 encoded "root"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
data:
  jwt-secret: N2YwNTRmNmQwNjdlMzgzYTJmNTRiZDFhMjQwODg3OWFjOWU3YjIyMTk5NWI5MzIzOTE4MzQ3ZWU2ZjBlMzQxYQ==  # base64 encoded
  mail-username: c2F5Zi5hYmlkaTFAZ21haWwuY29t  # base64 encoded "sayf.abidi1@gmail.com"
  mail-password: eWRwZSBnbmhoIG52bmwgYmJ6aQ==  # base64 encoded "ydpe gnhh nvnl bbzi"
  recaptcha-secret: NkxkRHVoY3JBQUFBQUtGSHQ1WEx0QXVDdWJjcFd6NFBJOFhfcDJucg==  # base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sonarqube
type: Opaque
data:
  postgres-password: YWRtaW4=
---
