apiVersion: apps/v1
kind: Deployment
metadata:
  name: approbation-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approbation-backend
  template:
    metadata:
      labels:
        app: approbation-backend
    spec:
      containers:
      - name: backend
        image: seifeddineabidi/approbation-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://approbation-mysql:3306/camunda?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Europe/Paris"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: APPLICATION_SECURITY_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: jwt-secret
        - name: SPRING_MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: mail-username
        - name: SPRING_MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: mail-password
        - name: RECAPTCHA_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: recaptcha-secret
        - name: OLLAMA_API_URL
          value: "http://approbation-ollama:11434/api/generate"
        - name: OLLAMA_API_MODEL
          value: "llama3.2"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: CAMUNDA_BPM_ADMIN_USER_ID
          value: "demo"
        - name: CAMUNDA_BPM_ADMIN_USER_PASSWORD
          value: "demo"
        - name: CAMUNDA_BPM_WEBAPP_CORS_ALLOWED_ORIGINS
          value: "http://approbation.local"
        resources:
          limits:
            cpu: "1000m"
            memory: "1024Mi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5