apiVersion: apps/v1
kind: Deployment
metadata:
  name: approbation-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approbation-backend
  template:
    metadata:
      labels:
        app: approbation-backend
    spec:
      containers:
      - name: backend
        image: seifeddineabidi/approbation-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/camunda?useSSL=false"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"