apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 1  # Reduced to 1 for resource efficiency
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: seifeddineabidi/approbation-backend:4eca3ab1319b8d8b25ca88a369e9530fa8ef4be3
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://approbation-mysql:3306/camunda?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Europe/Paris
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MySQL8Dialect
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: CAMUNDA_BPM_WEBAPP_CORS_ALLOWED_ORIGINS
              value: http://frontend.192.168.2.189.nip.io,http://localhost:3000
            - name: OLLAMA_API_URL
              value: http://approbation-ollama.default.svc.cluster.local:11434/api/generate
            - name: QUERY_API_URL
              value: http://backend-service.default.svc.cluster.local:8080/query/execute
            - name: CAMUNDA_ENGINE_URL
              value: http://backend-service.default.svc.cluster.local:8080/engine-rest
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120  
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5