apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.36
        command:
        - sh
        - -c
        - "until nc -z mysql-service 3306; do echo waiting for mysql; sleep 2; done;"
      containers:
      - name: backend
        image: seifeddineabidi/approbation-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/camunda?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Europe/Paris"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.MySQL8Dialect"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: CAMUNDA_BPM_WEBAPP_CORS_ALLOWED_ORIGINS
          value: "http://frontend.192.168.162.72.nip.io"
        - name: OLLAMA_API_URL
          value: "http://localhost:11434/api/generate"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60  # Increased delay to allow DB connection
          periodSeconds: 10