apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: approbation
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SeifeddineABIDI/k8s-manifests.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true