apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: approbation-suite
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SeifeddineABIDI/k8s-manifests.git
    targetRevision: HEAD
    path: manifests
    kustomize:
      namePrefix: approbation-
      commonLabels:
        app: approbation
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true