apiVersion: apps/v1
kind: Deployment
metadata:
  name: approbation-ollama
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approbation-ollama
  template:
    metadata:
      labels:
        app: approbation-ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:0.3.10
        ports:
        - containerPort: 11434
        command: ["/bin/sh", "-c", "ollama serve & sleep 10 && ollama pull llama3.2 && tail -f /dev/null"]
        resources:
          limits:
            cpu: "2000m"
            memory: "4096Mi"
          requests:
            cpu: "1000m"
            memory: "2048Mi"
        livenessProbe:
          httpGet:
            path: /api/version
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: ollama-models
          mountPath: /root/.ollama
      volumes:
      - name: ollama-models
        persistentVolumeClaim:
          claimName: ollama-models